### ISSUE TITLE
Is the DivKit Playground Open Source or Planned to be Open Sourced?

### ISSUE THREAD

**Issue by aliazimoshan** [divkit/divkit#47]
Hello,

I have been exploring the DivKit project and noticed the [DivKit Playground](https://divkit.tech/playground) available on your website. It's a fantastic tool for experimenting with DivKit features.

However, I could not find the source code for the playground in the repository. I have a few questions:

1. Is the source code for the DivKit Playground currently available, and if so, where can I find it?
2. If it is not open source, are there any plans to make the DivKit Playground open source in the future?

Having access to the playground's source code would be incredibly beneficial for deeper exploration and customization. Thank you for your time and for providing such a powerful UI toolkit!

Best regards,
Ali Azimoshan

**Comment by 4eb0da** [comment]
Hello
Some parts of the code may be found here: https://github.com/divkit/divkit/tree/main/site
However, this code lacks two things:
1) package.json (this is mainly because of deploy-specific info)
2) Visual editor source code

We are thinking about the full open source code, but we don't have an exact date.
