### ISSUE TITLE
Overflow Error When JSON Exceeds Screen Height in Flutter Version

### ISSUE THREAD

**Issue by aliazimoshan** [divkit/divkit#49]
Hello,

I have encountered an issue in the Flutter version of DivKit. When the JSON content exceeds the screen height, the screen does not scroll and instead displays an overflow error.

**Steps to Reproduce:**
1. Load a JSON configuration where the content height exceeds the screen height.
2. Observe the overflow error and lack of scrolling.

**Expected Behavior:**
The screen should scroll to accommodate the content that exceeds the screen height.

**Actual Behavior:**
The screen displays an overflow error and does not scroll.

**Screenshots:**
![Screenshot (2)](https://github.com/user-attachments/assets/f621f7f7-7288-400e-9e69-ea3d857617a1)

**Environment:**
Flutter version: (3.22.1)

Additional Context:
We are working on integrating DivKit into our project and would like to help resolve this issue. Could you provide guidance on how to fix this problem?

Thank you for your assistance.

Best regards,

**Comment by MANA-Y** [comment]
This type of problem affects the demo playground screen. For other clients, the div element is placed in a scrolling area, which allows scrolling. We don't do this because there are now significant discrepancies in the layout and measurement of the graphical components of the screen.

We will deal with this issue in future versions.

**Comment by MANA-Y** [comment]
Fixed since divkit v0.4.0

**Comment by MANA-Y** [comment]
Uploading Screen Recording 2024-09-02 at 14.18.44.mov…
