### ISSUE TITLE
Flutter client-side support

### ISSUE THREAD

**Issue by SynteZZZ** [divkit/divkit#8]
Please vote via 👍 emoji on this issue if you'd like to see this feature.
Please use reaction button, not a comment.

**Comment by Didar83** [comment]
👍

**Comment by dimstr** [comment]
👍

**Comment by Dan-Crane** [comment]
Hi. Any update?
Do you need any help?

**Comment by divkit** [comment]
No update( if you could help it would be great19:45, 4 августа 2023 г., dani ***@***.***>:
Hi. Any update?
Do you need any help?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by Dan-Crane** [comment]
@divkit first step -- need to write a parser from json to widgets?

**Comment by divkit** [comment]
Yep.

**Comment by SynteZZZ** [comment]
Here you go: https://github.com/divkit/divkit/tree/main/client/flutter/divkit
